### PR TITLE
Milestone 1: Created the Application data architecture documentation

### PR DESCRIPTION
**Pull request by Tekcoder**
The ERD was prepared based on the specified business rules. Five tables were added where each entity was filled according to MVP principles.

-  User (ID, FirstName/LastName, Email, Password, Image_Link)

- Post (ID, user_id [fk], Title, Content)

- Comment (ID, user_id[fk], post_id[fk], body)

- Like (ID, user_id(Fk), post_id(Fk) )

- Friendship (user_id (Pk,Fk), friend_id (PK,Fk), status)

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required
Great work guys!
Some changes need to be made to the ER diagram before we proceed.
### REQUIRED
**User -> Post**
* The relationship between a user and post entity is `one to many`. A user can have several posts but a post can only belong to one user(the creator of the post).

**User -> Friendship**
* The relationship between a user and a friendship record is one to many.
This also the case in friend -> friendship relationship.
A user can be referenced in several friendship records but a specific friendship record can only belong to one user. This also applies to the friend user.

**User ->  Comment**
* The relationship between user and comment is `one to many`.
A user can create several comments but a comment only has one creator(user).

**User -> Like**
* The association between user and likes is also `one to many`.
A user can have many likes but a specific like only contains one user(liker).

**Post -> Comment**
* The relationship between Post and Comment is `one to many`
A post can have many comments but a specific comment can only belong to one post.

**Post -> Like**
* The relationship between Post and Like is `one to many`.
A post can have many likes but specific like can only belong to one post.

**After implementing the changes, submit another request for review.**

_Feel free to reach out via slack for any issue/clarification_

**Happy Coding :computer: 
Simon Wathigo**

**Comment by Tekcoder** [comment]
> 
> ## Changes Required
> 
> Great work guys!
> Some changes need to be made to the ER diagram before we proceed.
> ### REQUIRED
> 
> **User -> Post**
> 
>     * The relationship between a user and post entity is `one to many`. A user can have several posts but a post can only belong to one user(the creator of the post).
> 
> 
> **User -> Friendship**
> 
>     * The relationship between a user and a friendship record is one to many.
>       This also the case in friend -> friendship relationship.
>       A user can be referenced in several friendship records but a specific friendship record can only belong to one user. This also applies to the friend user.
> 
> 
> **User -> Comment**
> 
>     * The relationship between user and comment is `one to many`.
>       A user can create several comments but a comment only has one creator(user).
> 
> 
> **User -> Like**
> 
>     * The association between user and likes is also `one to many`.
>       A user can have many likes but a specific like only contains one user(liker).
> 
> 
> **Post -> Comment**
> 
>     * The relationship between Post and Comment is `one to many`
>       A post can have many comments but a specific comment can only belong to one post.
> 
> 
> **Post -> Like**
> 
>     * The relationship between Post and Like is `one to many`.
>       A post can have many likes but specific like can only belong to one post.
> 
> 
> **After implementing the changes, submit another request for review.**
> 
> _Feel free to reach out via slack for any issue/clarification_
> 
> **Happy Coding 💻 Simon Wathigo**

Thanks for your reply. However, you didn't mention where the issue is on the diagram. It will be helpful if you kindly mention where we're getting it wrong.

Thanks in advance

**Comment by Tekcoder** [comment]
Thanks for your reply. However, you didn't mention where the issue is on the diagram. It will be helpful if you kindly mention where we're getting it wrong.

Thanks in advance

**Review by uche-inyama — APPROVED** [review]
## Approved

Hi team :wave:

Your ERD diagram is approved. 

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Pull request merged**
